{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret | default (printf "%s-secrets" (include "vega-memory.fullname" .)) }}
  labels:
    {{- include "vega-memory.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.secret.apiKey | quote }}
{{- end }}
